# Special option if under cygwin (=compile with mingwin)
ifeq (Cygwin,$(OS))
EXTRALIBS += -lws2_32 -liphlpapi
testkey.exe-FLAGS := -mwindows
testlicense.exe-FLAGS := -mwindows
endif

ifeq (i586-mingw32msvc-gcc,$(CC))
EXTRALIBS += -lws2_32 -liphlpapi
testkey.exe-FLAGS := -mwindows
testlicense.exe-FLAGS := -mwindows
endif

ifeq (amd64-mingw32msvc-gcc,$(CC))
EXTRALIBS += -lws2_32 -liphlpapi
testkey.exe-FLAGS := -mwindows
testlicense.exe-FLAGS := -mwindows
endif
