/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DBMLib */

#ifndef _Included_DBMLib
#define _Included_DBMLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DBMLib
 * Method:    boundbool2raw
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_DBMLib_boundbool2raw
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     DBMLib
 * Method:    raw2bound
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DBMLib_raw2bound
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
