/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_DBMLib */

#ifndef _Included_lib_DBMLib
#define _Included_lib_DBMLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_DBMLib
 * Method:    boundbool2raw
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_lib_DBMLib_boundbool2raw
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     lib_DBMLib
 * Method:    raw2bound
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_lib_DBMLib_raw2bound
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
